### ISSUE TITLE
Posthog Worker CrashLoop Permission denied /code/celerybeat.pid

### ISSUE THREAD

**Issue by m-wack** [PostHog/charts-clickhouse#537]
## Bug description
I am trying to deploy this chart in OCP 4.9. Everything is fine except the Worker Pod not coming up. It CrashLoops with the following message:

```
SKIP_ASYNC_MIGRATIONS_SETUP=0 celery -A posthog worker -Ofair -n node@%h --without-gossip --without-mingle --without-heartbeat

rm: can't remove 'celerybeat.pid': No such file or directory
celerybeat.pid not found, proceeding
celery beat v4.4.7 (cliffs) is starting.

🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻
Skipping async migrations setup. This is unsafe in production!
🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺

{"event": "AXES: BEGIN LOG"}
{"event": "AXES: BEGIN LOG"}
{"event": "AXES: Using django-axes version 5.9.0"}
{"event": "AXES: Using django-axes version 5.9.0"}
{"event": "AXES: blocking by IP only."}
{"event": "AXES: blocking by IP only."}

🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻
Skipping async migrations setup. This is unsafe in production!
🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺

{"event": "AXES: BEGIN LOG"}
{"event": "AXES: BEGIN LOG"}
{"event": "AXES: Using django-axes version 5.9.0"}
{"event": "AXES: Using django-axes version 5.9.0"}
{"event": "AXES: blocking by IP only."}
{"event": "AXES: blocking by IP only."}
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/platforms.py", line 149, in acquire
    self.write_pid()
  File "/usr/local/lib/python3.8/site-packages/celery/platforms.py", line 216, in write_pid
    pidfile_fd = os.open(self.path, PIDFILE_FLAGS, PIDFILE_MODE)
PermissionError: [Errno 13] Permission denied: '/code/celerybeat.pid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/usr/local/lib/python3.8/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python3.8/site-packages/celery/bin/celery.py", line 499, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python3.8/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/lib/python3.8/site-packages/celery/bin/celery.py", line 491, in handle_argv
    return self.execute(command, argv)
  File "/usr/local/lib/python3.8/site-packages/celery/bin/celery.py", line 415, in execute
    return cls(
  File "/usr/local/lib/python3.8/site-packages/celery/bin/base.py", line 308, in run_from_argv
    return self.handle_argv(prog_name,
  File "/usr/local/lib/python3.8/site-packages/celery/bin/base.py", line 393, in handle_argv
    return self(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/celery/bin/base.py", line 253, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/bin/beat.py", line 109, in run
    return beat().run()
  File "/usr/local/lib/python3.8/site-packages/celery/apps/beat.py", line 81, in run
    self.start_scheduler()
  File "/usr/local/lib/python3.8/site-packages/celery/apps/beat.py", line 92, in start_scheduler
    platforms.create_pidlock(self.pidfile)
  File "/usr/local/lib/python3.8/site-packages/celery/platforms.py", line 258, in create_pidlock
    pidlock = _create_pidlock(pidfile)
  File "/usr/local/lib/python3.8/site-packages/celery/platforms.py", line 268, in _create_pidlock
    pidlock.acquire()
  File "/usr/local/lib/python3.8/site-packages/celery/platforms.py", line 151, in acquire
    reraise(LockFailed, LockFailed(str(exc)), sys.exc_info()[2])
  File "/usr/local/lib/python3.8/site-packages/vine/five.py", line 194, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/celery/platforms.py", line 149, in acquire
    self.write_pid()
  File "/usr/local/lib/python3.8/site-packages/celery/platforms.py", line 216, in write_pid
    pidfile_fd = os.open(self.path, PIDFILE_FLAGS, PIDFILE_MODE)
celery.platforms.LockFailed: [Errno 13] Permission denied: '/code/celerybeat.pid'
Operations to perform:
  Apply all migrations: admin, auth, axes, contenttypes, ee, posthog, rest_hooks, sessions, social_django
Running migrations:
  No migrations to apply.

🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻
Skipping async migrations setup. This is unsafe in production!
🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺

{"event": "AXES: BEGIN LOG"}
{"event": "AXES: BEGIN LOG"}
{"event": "AXES: Using django-axes version 5.9.0"}
{"event": "AXES: Using django-axes version 5.9.0"}
{"event": "AXES: blocking by IP only."}
{"event": "AXES: blocking by IP only."}
List of clickhouse migrations to be applied:
Clickhouse migrations up to date!
```

This is my values.yaml:

```
posthog:
  cloud: other

  saml:
    enforced: false
    disabled: true

  service:
    name: posthog
    type: ClusterIP

  ingress:
    enabled: false
    nginx:
      enabled: false

  postgresql:
    enabled: true
    nameOverride: posthog-postgresql
    postgresqlDatabase: XXXXX
    postgresqlPassword: XXXXXXX
    persistence:
      enabled: true
      size: 20Gi
      storageClass: nfs-client

  redis:
    enabled: true
    serviceAccount:
      create: false
      name: default
    nameOverride: "posthog-redis"
    architecture: standalone
    master:
      persistence:
        enabled: true
        size: 5Gi
        storageClass: nfs-client

  kafka:
    enabled: true
    serviceAccount:
      create: false
      name: default
    nameOverride: posthog-kafka
    persistence:
      enabled: true
      size: 20Gi
      storageClass: nfs-client

  clickhouse:
    enabled: true
    user: admin
    existingSecret: XXXX
    existingSecretPasswordKey: XXXX
    persistence:
      enabled: true
      storageClass: nfs-client
      size: 20Gi
```

## Expected behavior
The Container starts without errors. 

## Actual behavior
It CrashLoops with an Permissions Error.

## How to reproduce

1. use my values.yaml
2. deploy to OCP 4.9

## Environment

- [x] Deployment platform (AWS/Azure/DigitalOcean/GCP/...): OCP 4.9
- [x] k8s version (server version from `kubectl version`): v1.22.1
- [x] Chart version/commit (`helm list -n posthog`): latest, 26.4.4

**Comment by guidoiaquinti** [comment]
👋 Hi @m-wack! What is OCP 4.9? Is it OpenShift Container Platform? If yes, we don't officially support it but we'll try to help you anyway. 

The error seems to be a permission issue trying to write to `/code/celerybeat.pid`. Can you please check the permission of the container? Are you running it in read only mode?

**Comment by m-wack** [comment]
Hi @guidoiaquinti, correct, it's OpenShift Container Platform. I installed it using the default helm chart provided by you.

When I look at the YAML definition of a pod for the worker, the only permissions related thing in the container's spec I can see is this one:

     ```
 securityContext:
        capabilities:
          drop:
            - KILL
            - MKNOD
            - SETGID
            - SETUID
        runAsUser: 1001040000
```

I haven't set any of this manually and just deployed the chart using above values. I also tried enabling Container Security Context in the values.yaml for the worker but that didn't help. 

I spun up a debug container and indeed the user is 1001040000. The /code folder is owned by posthog:posthog.

**Comment by m-wack** [comment]
I just did some more testing: what worked for me was setting 
      serviceAccount: default
for the main-container. Then I was able to specify 
          securityContext:
            runAsUser: 100
            
I got the UID 100 from the debug container. Now everything's working. 

This is the full container spec now:

```
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: posthog-workers
          command:
            - ./bin/docker-worker-celery
            - '--with-scheduler'
          env:
            - name: KAFKA_HOSTS
              value: 'posthog-posthog-kafka:9092'
            - name: KAFKA_URL
              value: 'kafka://posthog-posthog-kafka:9092'
            - name: POSTHOG_REDIS_HOST
              value: posthog-posthog-redis-master
            - name: POSTHOG_REDIS_PORT
              value: '6379'
            - name: PRIMARY_DB
              value: clickhouse
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: posthog
                  key: posthog-secret
            - name: SITE_URL
              value: 'http://127.0.0.1:8000'
            - name: DEPLOYMENT
              value: helm_other_ha
            - name: CAPTURE_INTERNAL_METRICS
              value: 'true'
            - name: HELM_INSTALL_INFO
              value: >-
                {"chart_version":"26.4.4","cloud":"other","deployment_type":"helm","hostname":null,"ingress_type":"","kube_version":"v1.22.0","operation":"install","release_name":"posthog","release_revision":1}
            - name: LOGGING_FORMATTER_NAME
              value: json
            - name: SENTRY_DSN
            - name: POSTHOG_POSTGRES_HOST
              value: posthog-pgbouncer
            - name: POSTHOG_POSTGRES_PORT
              value: '6543'
            - name: POSTHOG_DB_USER
              value: postgres
            - name: POSTHOG_DB_NAME
              value: posthog
            - name: POSTHOG_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: posthog-posthog-postgresql
                  key: postgresql-password
            - name: USING_PGBOUNCER
              value: 'true'
            - name: CLICKHOUSE_HOST
              value: clickhouse-posthog
            - name: CLICKHOUSE_CLUSTER
              value: posthog
            - name: CLICKHOUSE_DATABASE
              value: posthog
            - name: CLICKHOUSE_USER
              value: admin
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clickhouse-admin
                  key: admin-password
            - name: CLICKHOUSE_SECURE
              value: 'false'
            - name: CLICKHOUSE_VERIFY
              value: 'false'
            - name: EMAIL_HOST
            - name: EMAIL_PORT
            - name: EMAIL_HOST_USER
            - name: EMAIL_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: posthog
                  key: smtp-password
            - name: EMAIL_USE_TLS
              value: 'true'
            - name: EMAIL_USE_SSL
              value: 'false'
            - name: DEFAULT_FROM_EMAIL
          securityContext:
            runAsUser: 100
          ports:
            - containerPort: 8000
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          image: 'posthog/posthog:release-1.38.1'
      serviceAccount: default
      dnsPolicy: ClusterFirst
```

So for a fix I'd need to be able to specify the ServiceAccount in the values.yaml and the container show set the 'runAsUser' Context by itself.

**Comment by guidoiaquinti** [comment]
Can you share which `StorageClass` you are using? I have the feeling you might be using a NFS like storage instead of block storage.

**Comment by m-wack** [comment]
That is correct, we are using NFS storage. It's named `nfs-client` in our case.

**Comment by guidoiaquinti** [comment]
Cool, that's the underlying issue. Please use a non-NFS storage or you'll likely end up with problems. 

I'm closing this issue as it doesn't seems to be a bug of the chart.
